# Generated by Django 5.1.3 on 2024-11-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='department',
            field=models.CharField(choices=[('渉外', '渉外'), ('音響', '音響'), ('医務', '医務'), ('広報', '広報'), ('衣装', '衣装'), ('会場', '会場'), ('対外交渉', '対外交渉'), ('映像', '映像'), ('美術', '美術'), ('その他', 'その他')], max_length=10),
        ),
    ]
