# Generated by Django 5.1.3 on 2024-12-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_expense_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_name', models.CharField(choices=[('公演費', '公演費'), ('月会費', '月会費'), ('ダンパ費', 'ダンパ費')], max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
