# Generated by Django 5.1.3 on 2024-12-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_expensecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('generation', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='category_name',
            field=models.CharField(choices=[('公演費', '公演費'), ('月会費', '月会費'), ('ベースメント費', 'ベースメント費')], max_length=10),
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('members', models.ManyToManyField(related_name='payment_items', to='accounting.member')),
            ],
        ),
    ]
