# Generated by Django 5.1.3 on 2024-12-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_paymentitem_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.member')),
                ('payment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.paymentitem')),
            ],
            options={
                'unique_together': {('member', 'payment_item')},
            },
        ),
    ]
